src/Presentation/WebUI/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Categories;

namespace WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        [Authorize(Policy = "admin.categories.get")]
        public async Task<IActionResult> Index()
        {
            var data = await categoryService.GetAllAsync();

            return View(data);
        }

        [Authorize(Policy = "admin.categories.get")]
        public async Task<IActionResult> Details(int id)
        {
            var data = await categoryService.GetByIdAsync(id);

            return View(data);
        }

        [Authorize(Policy = "admin.categories.add")]
        public IActionResult Create()
        {
            throw new ArgumentNullException();
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "admin.categories.add")]
        public async Task<IActionResult> Create(AddCategoryRequestDto model)
        {
            await categoryService.AddAsync(model);

            return RedirectToAction("Index");
        }

        [Authorize(Policy = "admin.categories.edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var data = await categoryService.GetByIdAsync(id);

            return View(data);
        }

        [HttpPost]
        [Authorize(Policy = "admin.categories.edit")]
        public async Task<IActionResult> Edit(EditCategortDto model)
        {
            await categoryService.EditAsync(model);

            return RedirectToAction("Index");
        }

        [Authorize(Policy = "admin.categories.remove")]
        public async Task<IActionResult> Remove(int id)
        {
            throw new ArgumentNullException();

            await categoryService.RemoveAsync(id);

            return Json(new
            {
                error = false,
                message = "ok"
            });
        }
    }
}

src/Presentation/WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Presentation/WebUI/Areas/Admin/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Tags;

namespace WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TagsController : Controller
    {
        private readonly ITagService tagService;

        public TagsController(ITagService tagService)
        {
            this.tagService = tagService;
        }

        [Authorize(Policy = "admin.tags.get")]
        public async Task<IActionResult> Index()
        {
            var response = await tagService.GetAllASync();
            return View(response);
        }

        [Authorize(Policy = "admin.tags.get")]
        public async Task<IActionResult> Details(int id)
        {
            var response = await tagService.GetById(id);
            return View(response);
        }

        [Authorize(Policy = "admin.tags.add")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "admin.tags.add")]
        public async Task<IActionResult> Create(AddTagRequestDto model)
        {
            await tagService.AddAsync(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Presentation/WebUI/Areas/Admin/Views/Shared/_Preloader.cshtml
<div class="theme-loader">
    <div class="ball-scale">
        <div class='contain'>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
        </div>
    </div>
</div>

src/Presentation/WebUI/Areas/Admin/Views/Shared/_Sidebar.cshtml
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu">
        <div class="pcoded-navigatio-lavel">Əməliyyat</div>
        <ul class="pcoded-item pcoded-left-item">
            <li>
                <a asp-controller="Dashboard" asp-action="Index">
                    <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                    <span class="pcoded-mtext">Ana səhifə</span>
                </a>
            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-shopping-cart"></i></span>
                    <span class="pcoded-mtext">Məhsullar</span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a>
                            <span class="pcoded-mtext">Məhsullar</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="pcoded-mtext">Kompaniyalar</span>
                            <span class="pcoded-badge label label-info">NEW</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="pcoded-mtext">Tükənən məhsullar</span>
                            <span class="pcoded-badge label label-danger">5</span>
                        </a>
                    </li>

                    @if (User.HasAccess("admin.categories.get"))
                    {
                        <li>
                            <a asp-controller="Categories" asp-action="Index">
                                <span class="pcoded-micon"><i class="feather icon-menu"></i></span>
                                <span class="pcoded-mtext">Kateqoriyalar</span>
                            </a>
                        </li>
                    }
                </ul>
            </li>  
            @if (User.HasAccess("admin.tags.get"))
            {
                <li>
                    <a asp-controller="Tags" asp-action="Index">
                        <span class="pcoded-micon"><i class="feather icon-menu"></i></span>
                        <span class="pcoded-mtext">Təqlər</span>
                    </a>
                </li>
            }
           
        </ul>
        <ul class="pcoded-item pcoded-left-item">
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-feather"></i></span>
                    <span class="pcoded-mtext">Paylaşımlar</span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a>
                            <span class="pcoded-mtext">Dərc edilmişlər</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="pcoded-mtext">Gözləmədə</span>
                            <span class="pcoded-badge label label-info">2</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <span class="pcoded-mtext">İmtina edilib</span>
                            <span class="pcoded-badge label label-danger">5</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="pcoded-navigatio-lavel">Tənzimləmələr</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                    <span class="pcoded-mtext">Dashboard</span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a href="default/index.html">
                            <span class="pcoded-mtext">Default</span>
                        </a>
                    </li>
                    <li>
                        <a href="default/dashboard-crm.html">
                            <span class="pcoded-mtext">CRM</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="default/dashboard-analytics.html">
                            <span class="pcoded-mtext">Analytics</span>
                            <span class="pcoded-badge label label-info ">NEW</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="default/navbar-light.html">
                    <span class="pcoded-micon"><i class="feather icon-menu"></i></span>
                    <span class="pcoded-mtext">Navigation</span>
                </a>
            </li>
        </ul>
    </div>
</nav>