src/Presentation/WebUI/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers
{
    public class BlogController : Controller
    {
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            return View();
        }

        public IActionResult LeaveComment(int id)
        {
            return View();
        }
    }
}

src/Presentation/WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers
{
    public class ShopController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            return View();
        }

        public IActionResult Basket()
        {
            return View();
        }

        public IActionResult Checkout()
        {
            return View();
        }
    }
}

src/Presentation/WebUI/Views/Shared/_Categories.cshtml
@model IEnumerable<CategoryGetAllDto>

<div class="hero__categories">
    <div class="hero__categories__all">
        <i class="fa fa-bars"></i>
        <span>All Categories</span>
    </div>
    <ul>
        @foreach (var item in Model)
        {
            <li><a href="#">@item.Name</a></li>
        }
    </ul>
</div>

src/Presentation/WebUI/Views/Shared/_Layout.cshtml
@{
    string? message = TempData["Message"] as string;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ogani | @ViewBag.Title</title>

    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&amp;display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/style.css" type="text/css">
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
    @await RenderSectionAsync("addcss", required: false)
</head>
<body>

    <div id="preloder">
        <div class="loader"></div>
    </div>

    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="#"><img src="~/assets/img/logo.png" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                <li><a asp-controller="Shop" asp-action="Basket"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
            </ul>
            <div class="header__cart__price">item: <span>$150.00</span></div>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__language">
                <img src="~/assets/img/language.png" alt="">
                <div>English</div>
                <span class="arrow_carrot-down"></span>
                <ul>
                    <li><a href="#">Spanis</a></li>
                    <li><a href="#">English</a></li>
                </ul>
            </div>
            <div class="header__top__right__auth">
                <a href="#"><i class="fa fa-user"></i> Login</a>
            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="shop" asp-action="index">Shop</a></li>
                <li>
                    <a href="#">Pages</a>
                    <ul class="header__menu__dropdown">
                        <li><a href="shop-details.html">Shop Details</a></li>
                        <li><a href="shoping-cart.html">Shoping Cart</a></li>
                        <li><a href="checkout.html">Check Out</a></li>
                        <li><a href="blog-details.html">Blog Details</a></li>
                    </ul>
                </li>
                <li><a href="blog.html">Blog</a></li>
                <li><a asp-controller="Home" asp-action="contact">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
        <div class="humberger__menu__contact">
            <ul>
                <li><i class="fa fa-envelope"></i> <a href="https://colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="9ef6fbf2f2f1defdf1f2f1ecf2f7fcb0fdf1f3">[email&#160;protected]</a></li>
                <li>Free Shipping for all Order of $99</li>
            </ul>
        </div>
    </div>


    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i> <a href="https://colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="5e363b3232311e3d3132312c32373c703d3133">[email&#160;protected]</a></li>
                                <li>Free Shipping for all Order of $99</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-pinterest-p"></i></a>
                            </div>
                            <div class="header__top__right__language">
                                <img src="~/assets/img/language.png" alt="">
                                <div>English</div>
                                <span class="arrow_carrot-down"></span>
                                <ul>
                                    <li><a href="#">Spanis</a></li>
                                    <li><a href="#">English</a></li>
                                </ul>
                            </div>
                            <div class="header__top__right__auth">
                                <a href="#"><i class="fa fa-user"></i> Login</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a asp-controller="Home" asp-action="Index"><img src="~/assets/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <partial name="_Navbar" />
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                            <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                            <li><a asp-controller="Shop" asp-action="Basket"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
                        </ul>
                        <div class="header__cart__price">item: <span>$150.00</span></div>
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>

    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-info">
            @message
        </div>
    }

    @RenderBody()


    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a asp-controller="Home" asp-action="Index"><img src="~/assets/img/logo.png" alt=""></a>
                        </div>
                        <ul>
                            <li>Address: 60-49 Road 11378 New York</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: <a href="https://colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="335b565f5f5c73505c5f5c415f5a511d505c5e">[email&#160;protected]</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Delivery infomation</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Who We Are</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Innovation</a></li>
                            <li><a href="#">Testimonials</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form method="post" id="subscribe">
                            <input type="text" name="email" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__copyright">
                        <div class="footer__copyright__text">
                            <p>
                                Copyright &copy;<script type="text/javascript">document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>
                            </p>
                        </div>
                        <div class="footer__copyright__payment"><img src="~/assets/img/payment-item.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <script src="~/assets/js/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="~/assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/js/jquery.nice-select.min.js" type="text/javascript"></script>
    <script src="~/assets/js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="~/assets/js/jquery.slicknav.js" type="text/javascript"></script>
    <script src="~/assets/js/mixitup.min.js" type="text/javascript"></script>
    <script src="~/assets/js/owl.carousel.min.js" type="text/javascript"></script>
    <script src="~/assets/js/main.js" type="text/javascript"></script>
    <script src="~/lib/toastr.js/toastr.min.js" type="text/javascript"></script>
    <script src="~/assets/js/overrides/toastr.override.js" type="text/javascript"></script>

    <script>
        const frm = document.querySelector('#subscribe');

        frm.addEventListener('submit', function (e) {
            e.preventDefault();

            const element = e.currentTarget;

            const formData = new FormData(e.currentTarget);

            fetch(`@Url.Action("Subscribe", "Home")`, {
                method: 'POST',
                body: formData
            })
                .then(response => response.json())
                .then(response => {

                    if (response.error == false) {
                        toastr.success(response.message, "Success");
                        element.reset();
                        return;
                    }

                    toastr.warning(response.message, "Diqqət");
                })
                .catch(e => {
                    console.error(e);
                });
        });

    </script>

    @await RenderSectionAsync("addjs", required: false)
</body>
</html>

src/Presentation/WebUI/Views/Shared/_Navbar.cshtml
<nav class="header__menu">
    <ul>
        <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li><a asp-controller="shop" asp-action="index">Shop</a></li>
@*         <li>
            <a href="#">Pages</a>
            <ul class="header__menu__dropdown">
                <li><a href="shop-details.html">Shop Details</a></li>
                <li><a href="shoping-cart.html">Shoping Cart</a></li>
                <li><a href="checkout.html">Check Out</a></li>
                <li><a href="blog-details.html">Blog Details</a></li>
            </ul>
        </li> *@
        <li><a asp-controller="Blog" asp-action="index">Blog</a></li>
        <li><a asp-controller="Home" asp-action="contact">Contact</a></li>
    </ul>
</nav>